parameters:
    jb_fileuploader.file_ajax.upload_listener.class: Jb\Bundle\FileUploaderBundle\EventListener\Upload\UploadListener
    jb_fileuploader.file_ajax.validation_listener.class: Jb\Bundle\FileUploaderBundle\EventListener\Validation\ConfiguredValidationListener
    jb_fileuploader.file_history.manager.class: Jb\Bundle\FileUploaderBundle\Service\FileHistoryManager
    jb_fileuploader.endpoint_configuration.class: Jb\Bundle\FileUploaderBundle\Service\EndpointConfiguration
    jb_fileuploader.twig_extension.crop.class: Jb\Bundle\FileUploaderBundle\Twig\CropExtension
    jb_fileuploader.croper.class: Jb\Bundle\FileUploaderBundle\Service\Croper
    jb_fileuploader.crop.manager.class: Jb\Bundle\FileUploaderBundle\Service\CropFileManager

services:
    jb_fileuploader.file_ajax.upload_listener:
        class: %jb_fileuploader.file_ajax.upload_listener.class%
        scope: request
        arguments:
            - @jb_fileuploader.file_history.manager
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    jb_fileuploader.file_ajax.validation_listener:
        class: %jb_fileuploader.file_ajax.validation_listener.class%
        arguments:
            - @jb_fileuploader.validator.manager
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.validation, method: onValidate }

    jb_fileuploader.file_history.manager:
        class: %jb_fileuploader.file_history.manager.class%
        scope: request
        arguments:
            - @doctrine.orm.entity_manager
            - @security.context
            - @jb_fileuploader.resolver_chain
            - @jb_fileuploader.endpoint_configuration

    jb_fileuploader.endpoint_configuration:
        class: %jb_fileuploader.endpoint_configuration.class%
        arguments:
            - %jb_fileuploader.endpoints%

    jb_fileuploader.twig_extension.crop:
        class: %jb_fileuploader.twig_extension.crop.class%
        arguments:
            - @router
            - %jb_fileuploader.crop_route%
        tags:
            - { name: twig.extension }

    jb_fileuploader.croper:
        class: "%jb_fileuploader.croper.class%"
        scope: request
        arguments:
            - @jb_fileuploader.crop.manager
            - @jb_fileuploader.resolver_chain
            - @jb_fileuploader.endpoint_configuration
            - @jb_fileuploader.validator.manager

    jb_fileuploader.crop.manager:
        class: "%jb_fileuploader.crop.manager.class%"
        arguments:
            - @liip_imagine.data.manager
            - @liip_imagine.filter.manager
            - @knp_gaufrette.filesystem_map
            - @jb_fileuploader.endpoint_configuration